DATASET:
  TYPE: CUHK_SYSU
  PATH: !include configs/_path_cuhk_sysu.yaml
  BATCH_SIZE: 5
SOLVER:
  MAX_EPOCHS: 20
  OPTIMIZER: 'Adam'
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.0
  BIAS_LR_FACTOR: 1.0
  BIAS_DECAY: 0.0
  SGD_MOMENTUM: 0.0
  LR_DECAY_MILESTONES: [8, 14]
  LR_DECAY_GAMMA: 0.1
MODEL:
  BACKBONE: 'ConvNeXt'
  REID:
    LOSS:
      LUT_SIZE: 5532
      CQ_SIZE: 5000
      MARGIN: 0.25
  PARAM_INIT: 'v1'
