DATASET:
  TYPE: PRW
  PATH: !include configs/_path_prw.yaml
  BATCH_SIZE: 8
SOLVER:
  MAX_EPOCHS: 20
  OPTIMIZER: 'SGD'
  BASE_LR: 0.003
  WEIGHT_DECAY: 0.0005
  BIAS_LR_FACTOR: 1.
  BIAS_DECAY: 0.0005
  SGD_MOMENTUM: 0.9
  LR_DECAY_MILESTONES: [8, 14]
  LR_DECAY_GAMMA: 0.1
MODEL:
  BACKBONE: 'SOLIDER'
  REID:
    LOSS:
      LUT_SIZE: 483
      CQ_SIZE: 500
      MARGIN: 0.35
  PARAM_INIT: 'v2'
